# TODO: COMPLETE ME	

[window]
width = 1280
height = 720

[player]
lives = 3
level_max_time = 90000
highscore_filename = "highscores.json"

[level]
width = 23
height = 14
width = 11 # i have no idea why 
height = 11


[ghost]
points_per_ghost = 200


# config = {
#     "highscore_filename": "highscores.json",
#     "level": [
#         {"width": 23, "height": 14},
#         {"width": 11, "height": 11},
#     ],
#     "lives": 3,
#     "points_per_pacgum": 15,
#     "points_per_super_pacgum": 50,
#     "points_per_ghost": 200,
#     "level_max_time": 90000,
# }
